
#!/usr/bin/env bash
#set -e
FQDN="localhost"

# coap-gateway
FIRMWARE_COAP_PORT=5682
FIRMWARE_COAP_ADDRESS="0.0.0.0:$FIRMWARE_COAP_PORT"
FIRMWARE_COAP_DISABLE_VERIFY_CLIENTS=true
FIRMWARE_COAP_BLOCKWISE_TRANSFER_SZX=1024
FIRMWARE_COAP_LOG_MESSAGES=true

export CERTIFICATES_PATH="./certs"
export LOGS_PATH="/data/log"

export INTERNAL_CERT_DIR_PATH="$CERTIFICATES_PATH/internal"

# ROOT CERTS
export CA_POOL_DIR="$CERTIFICATES_PATH"
export CA_POOL_NAME_PREFIX="root_ca"
export CA_POOL_CERT_PATH="$CA_POOL_DIR/$CA_POOL_NAME_PREFIX.crt"
export CA_POOL_CERT_KEY_PATH="$CA_POOL_DIR/$CA_POOL_NAME_PREFIX.key"


#LISTEN CERTS
export LISTEN_TYPE="file"
export LISTEN_FILE_CA_POOL="$CA_POOL_CERT_PATH"


export EXTERNAL_CERT_DIR_PATH="$CERTIFICATES_PATH/external"

export FIRMWARE_COAP_FILE_CERT_NAME="firmware-coap.crt"
export FIRMWARE_COAP_FILE_CERT_KEY_NAME="firmware-coap.key"

export COAP_GATEWAY_UNSECURE_FQDN=$FQDN
export COAP_GATEWAY_FQDN=$FQDN

echo "generating COAP-GW cert"
#certificate-generator --cmd.generateIdentityCertificate=$COAP_GATEWAY_CLOUD_ID --outCert=$EXTERNAL_CERT_DIR_PATH/$COAP_GATEWAY_FILE_CERT_NAME --outKey=$EXTERNAL_CERT_DIR_PATH/$COAP_GATEWAY_FILE_CERT_KEY_NAME --cert.san.domain=$COAP_GATEWAY_FQDN --signerCert=$CA_POOL_CERT_PATH --signerKey=$CA_POOL_CERT_KEY_PATH


echo "starting coap-gateway-secure"
export ADDRESS=${FIRMWARE_COAP_ADDRESS} \
export LOG_MESSAGES=${FIRMWARE_COAP_LOG_MESSAGES} \
export EXTERNAL_PORT=${FIRMWARE_COAP_PORT} \
export FQDN=${FIRMWARE_COAP_FQDN} \
#need to export variable to make it available to subprocess
export LISTEN_FILE_CERT_DIR_PATH=${EXTERNAL_CERT_DIR_PATH} \
export LISTEN_FILE_CERT_NAME=${FIRMWARE_COAP_FILE_CERT_NAME} \
export LISTEN_FILE_CERT_KEY_NAME=${FIRMWARE_COAP_FILE_CERT_KEY_NAME} \
export LISTEN_FILE_DISABLE_VERIFY_CLIENT_CERTIFICATE=${FIRMWARE_COAP_DISABLE_VERIFY_CLIENTS} \
export DISABLE_BLOCKWISE_TRANSFER=false \ # Blockwise has to be enabled in order to get the firmware
export BLOCKWISE_TRANSFER_SZX=${FIRMWARE_COAP_BLOCKWISE_TRANSFER_SZX} \
export DISABLE_PEER_TCP_SIGNAL_MESSAGE_CSMS=${FIRMWARE_COAP_DISABLE_PEER_TCP_SIGNAL_MESSAGE_CSMS} 
./test

